//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllMyBio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AllMyBioDbEntities : DbContext
    {
        public AllMyBioDbEntities()
            : base("name=AllMyBioDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<domain> domains { get; set; }
        public virtual DbSet<link> links { get; set; }
        public virtual DbSet<package> packages { get; set; }
        public virtual DbSet<page> pages { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<setting> settings { get; set; }
        public virtual DbSet<track_links> track_links { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<users_logs> users_logs { get; set; }
    }
}
