//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllMyBio
{
    using System;
    using System.Collections.Generic;
    
    public partial class domain
    {
        public int domain_id { get; set; }
        public int user_id { get; set; }
        public string scheme { get; set; }
        public string host { get; set; }
        public Nullable<sbyte> type { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual user user { get; set; }
    }
}
