//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgBubble
{
    using System;
    using System.Collections.Generic;
    
    public partial class general_file_manager
    {
        public int id { get; set; }
        public string ids { get; set; }
        public Nullable<int> uid { get; set; }
        public string file_name { get; set; }
        public string image_type { get; set; }
        public string file_ext { get; set; }
        public string file_size { get; set; }
        public string is_image { get; set; }
        public Nullable<int> image_width { get; set; }
        public Nullable<int> image_height { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
