//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgBubble
{
    using System;
    using System.Collections.Generic;
    
    public partial class general_proxies
    {
        public int id { get; set; }
        public string ids { get; set; }
        public string address { get; set; }
        public string location { get; set; }
        public Nullable<int> limit { get; set; }
        public Nullable<int> package { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> changed { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
