//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgBubble
{
    using System;
    using System.Collections.Generic;
    
    public partial class general_custom_page
    {
        public int id { get; set; }
        public string ids { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> position { get; set; }
        public string name { get; set; }
        public string slug { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public string content { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> changed { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
