//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgBubble
{
    using System;
    using System.Collections.Generic;
    
    public partial class general_coupons
    {
        public int id { get; set; }
        public string ids { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<float> price { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public string packages { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> changed { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
