//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgBubble
{
    using System;
    using System.Collections.Generic;
    
    public partial class general_payment_subscriptions
    {
        public int id { get; set; }
        public string ids { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> package { get; set; }
        public string type { get; set; }
        public string billing_agreement_id { get; set; }
        public Nullable<int> plan { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
