//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgBubble
{
    using System;
    using System.Collections.Generic;
    
    public partial class general_users
    {
        public int id { get; set; }
        public string ids { get; set; }
        public Nullable<int> admin { get; set; }
        public string login_type { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> package { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public string timezone { get; set; }
        public string permission { get; set; }
        public string settings { get; set; }
        public string activation_key { get; set; }
        public string reset_key { get; set; }
        public string history_ip { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> changed { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
