//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgBubble
{
    using System;
    using System.Collections.Generic;
    
    public partial class general_purchase
    {
        public int id { get; set; }
        public string ids { get; set; }
        public string pid { get; set; }
        public string purchase_code { get; set; }
        public string version { get; set; }
    }
}
