//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgBubble
{
    using System;
    using System.Collections.Generic;
    
    public partial class instagram_accounts
    {
        public int id { get; set; }
        public string ids { get; set; }
        public string uid { get; set; }
        public string pid { get; set; }
        public string avatar { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string proxy { get; set; }
        public Nullable<int> default_proxy { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> changed { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
