//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgBubble
{
    using System;
    using System.Collections.Generic;
    
    public partial class instagram_activities_log
    {
        public int id { get; set; }
        public string ids { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> pid { get; set; }
        public string action { get; set; }
        public string user_id { get; set; }
        public string media_id { get; set; }
        public string data { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
