//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Products
{
    using System;
    using System.Collections.Generic;
    
    public partial class sp_account_manager
    {
        public long id { get; set; }
        public string ids { get; set; }
        public string social_network { get; set; }
        public string category { get; set; }
        public Nullable<int> team_id { get; set; }
        public Nullable<int> login_type { get; set; }
        public Nullable<int> can_post { get; set; }
        public string pid { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string token { get; set; }
        public string avatar { get; set; }
        public string url { get; set; }
        public string data { get; set; }
        public string proxy { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> changed { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
