//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Products
{
    using System;
    using System.Collections.Generic;
    
    public partial class sp_file_manager
    {
        public long id { get; set; }
        public string ids { get; set; }
        public Nullable<int> team_id { get; set; }
        public string name { get; set; }
        public string file { get; set; }
        public string type { get; set; }
        public string extension { get; set; }
        public Nullable<float> size { get; set; }
        public Nullable<int> is_image { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
