//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Products
{
    using System;
    using System.Collections.Generic;
    
    public partial class sp_instagram_activities
    {
        public int id { get; set; }
        public string ids { get; set; }
        public Nullable<int> team_id { get; set; }
        public Nullable<int> pid { get; set; }
        public string account { get; set; }
        public string action { get; set; }
        public Nullable<int> time { get; set; }
        public string data { get; set; }
        public string settings { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> changed { get; set; }
        public Nullable<int> created { get; set; }
    }
}
