//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Products
{
    using System;
    using System.Collections.Generic;
    
    public partial class sp_language_category
    {
        public long id { get; set; }
        public string ids { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string icon { get; set; }
        public Nullable<int> is_default { get; set; }
        public Nullable<int> status { get; set; }
    }
}
