//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Products
{
    using System;
    using System.Collections.Generic;
    
    public partial class sp_payment_subscriptions
    {
        public int id { get; set; }
        public string ids { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> package { get; set; }
        public string type { get; set; }
        public string subscription_id { get; set; }
        public string customer_id { get; set; }
        public Nullable<int> plan { get; set; }
        public Nullable<int> created { get; set; }
    }
}
