//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Products
{
    using System;
    using System.Collections.Generic;
    
    public partial class sp_package_manager
    {
        public long id { get; set; }
        public string ids { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<float> price_monthly { get; set; }
        public Nullable<float> price_annually { get; set; }
        public Nullable<int> number_accounts { get; set; }
        public Nullable<int> trial_day { get; set; }
        public Nullable<int> popular { get; set; }
        public Nullable<int> position { get; set; }
        public string permissions { get; set; }
        public string data { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> changed { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
