//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Products
{
    using System;
    using System.Collections.Generic;
    
    public partial class sp_proxy_manager
    {
        public long id { get; set; }
        public string ids { get; set; }
        public string address { get; set; }
        public string location { get; set; }
        public string limit { get; set; }
        public string packages { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> changed { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
