//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Products
{
    using System;
    using System.Collections.Generic;
    
    public partial class sp_team_member
    {
        public int id { get; set; }
        public string ids { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> team_id { get; set; }
        public string permissions { get; set; }
    }
}
