//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Products
{
    using System;
    using System.Collections.Generic;
    
    public partial class sp_users
    {
        public int id { get; set; }
        public string ids { get; set; }
        public string pid { get; set; }
        public Nullable<int> role { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> package { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public string timezone { get; set; }
        public string login_type { get; set; }
        public string data { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> changed { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
