//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllMyBio
{
    using System;
    using System.Collections.Generic;
    
    public partial class track_links
    {
        public int id { get; set; }
        public int link_id { get; set; }
        public string dynamic_id { get; set; }
        public string ip { get; set; }
        public string location { get; set; }
        public string os { get; set; }
        public string browser { get; set; }
        public string referer { get; set; }
        public int count { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime last_date { get; set; }
    
        public virtual link link { get; set; }
    }
}
