//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class aor_conditions
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.Guid> modified_user_id { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public string description { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.Guid> aor_report_id { get; set; }
        public Nullable<int> condition_order { get; set; }
        public string logic_op { get; set; }
        public string parenthesis { get; set; }
        public string module_path { get; set; }
        public string field { get; set; }
        public string @operator { get; set; }
        public string value_type { get; set; }
        public string value { get; set; }
        public Nullable<bool> parameter { get; set; }
    }
}
