//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class aos_pdf_templates
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.Guid> modified_user_id { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public string description { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.Guid> assigned_user_id { get; set; }
        public Nullable<bool> active { get; set; }
        public string type { get; set; }
        public string pdfheader { get; set; }
        public string pdffooter { get; set; }
        public Nullable<int> margin_left { get; set; }
        public Nullable<int> margin_right { get; set; }
        public Nullable<int> margin_top { get; set; }
        public Nullable<int> margin_bottom { get; set; }
        public Nullable<int> margin_header { get; set; }
        public Nullable<int> margin_footer { get; set; }
        public string page_size { get; set; }
        public string orientation { get; set; }
    }
}
