//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class aos_contracts
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.Guid> modified_user_id { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public string description { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.Guid> assigned_user_id { get; set; }
        public string reference_code { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<decimal> total_contract_value { get; set; }
        public Nullable<decimal> total_contract_value_usdollar { get; set; }
        public Nullable<System.Guid> currency_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> customer_signed_date { get; set; }
        public Nullable<System.DateTime> company_signed_date { get; set; }
        public Nullable<System.DateTime> renewal_reminder_date { get; set; }
        public string contract_type { get; set; }
        public Nullable<System.Guid> contract_account_id { get; set; }
        public Nullable<System.Guid> opportunity_id { get; set; }
        public Nullable<System.Guid> contact_id { get; set; }
        public Nullable<System.Guid> call_id { get; set; }
        public Nullable<decimal> total_amt { get; set; }
        public Nullable<decimal> total_amt_usdollar { get; set; }
        public Nullable<decimal> subtotal_amount { get; set; }
        public Nullable<decimal> subtotal_amount_usdollar { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public Nullable<decimal> discount_amount_usdollar { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> tax_amount_usdollar { get; set; }
        public Nullable<decimal> shipping_amount { get; set; }
        public Nullable<decimal> shipping_amount_usdollar { get; set; }
        public string shipping_tax { get; set; }
        public Nullable<decimal> shipping_tax_amt { get; set; }
        public Nullable<decimal> shipping_tax_amt_usdollar { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<decimal> total_amount_usdollar { get; set; }
    }
}
