//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class aos_line_item_groups
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.Guid> modified_user_id { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public string description { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.Guid> assigned_user_id { get; set; }
        public Nullable<decimal> total_amt { get; set; }
        public Nullable<decimal> total_amt_usdollar { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public Nullable<decimal> discount_amount_usdollar { get; set; }
        public Nullable<decimal> subtotal_amount { get; set; }
        public Nullable<decimal> subtotal_amount_usdollar { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> tax_amount_usdollar { get; set; }
        public Nullable<decimal> subtotal_tax_amount { get; set; }
        public Nullable<decimal> subtotal_tax_amount_usdollar { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<decimal> total_amount_usdollar { get; set; }
        public string parent_type { get; set; }
        public Nullable<System.Guid> parent_id { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<System.Guid> currency_id { get; set; }
    }
}
