//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaign
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.Guid> modified_user_id { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.Guid> assigned_user_id { get; set; }
        public int tracker_key { get; set; }
        public Nullable<int> tracker_count { get; set; }
        public string refer_url { get; set; }
        public string tracker_text { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string status { get; set; }
        public Nullable<int> impressions { get; set; }
        public Nullable<System.Guid> currency_id { get; set; }
        public Nullable<double> budget { get; set; }
        public Nullable<double> expected_cost { get; set; }
        public Nullable<double> actual_cost { get; set; }
        public Nullable<double> expected_revenue { get; set; }
        public string campaign_type { get; set; }
        public string objective { get; set; }
        public string content { get; set; }
        public string frequency { get; set; }
        public Nullable<System.Guid> survey_id { get; set; }
    }
}
