//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaign_log
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> campaign_id { get; set; }
        public string target_tracker_key { get; set; }
        public string target_id { get; set; }
        public string target_type { get; set; }
        public string activity_type { get; set; }
        public Nullable<System.DateTime> activity_date { get; set; }
        public string related_id { get; set; }
        public string related_type { get; set; }
        public Nullable<bool> archived { get; set; }
        public Nullable<int> hits { get; set; }
        public Nullable<System.Guid> list_id { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string more_information { get; set; }
        public Nullable<System.Guid> marketing_id { get; set; }
    }
}
