//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class cases_cstm
    {
        public System.Guid id_c { get; set; }
        public Nullable<float> jjwg_maps_lng_c { get; set; }
        public Nullable<float> jjwg_maps_lat_c { get; set; }
        public string jjwg_maps_geocode_status_c { get; set; }
        public string jjwg_maps_address_c { get; set; }
    }
}
