//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class cron_remove_documents
    {
        public string id { get; set; }
        public string bean_id { get; set; }
        public string module { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    }
}
