//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string symbol { get; set; }
        public string iso4217 { get; set; }
        public Nullable<double> conversion_rate { get; set; }
        public string status { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public System.Guid created_by { get; set; }
    }
}
