//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class document_revisions
    {
        public string id { get; set; }
        public string change_log { get; set; }
        public string document_id { get; set; }
        public string doc_id { get; set; }
        public string doc_type { get; set; }
        public string doc_url { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public string filename { get; set; }
        public string file_ext { get; set; }
        public string file_mime_type { get; set; }
        public string revision { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    }
}
