//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        public System.Guid id { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.Guid> modified_user_id { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public string description { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.Guid> assigned_user_id { get; set; }
        public string document_name { get; set; }
        public string doc_id { get; set; }
        public string doc_type { get; set; }
        public string doc_url { get; set; }
        public Nullable<System.DateTime> active_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public string category_id { get; set; }
        public string subcategory_id { get; set; }
        public string status_id { get; set; }
        public string document_revision_id { get; set; }
        public Nullable<System.Guid> related_doc_id { get; set; }
        public Nullable<System.Guid> related_doc_rev_id { get; set; }
        public Nullable<bool> is_template { get; set; }
        public string template_type { get; set; }
    }
}
