//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class email
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.Guid> modified_user_id { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.Guid> assigned_user_id { get; set; }
        public Nullable<bool> orphaned { get; set; }
        public Nullable<System.DateTime> last_synced { get; set; }
        public Nullable<System.DateTime> date_sent_received { get; set; }
        public string message_id { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public Nullable<bool> flagged { get; set; }
        public Nullable<bool> reply_to_status { get; set; }
        public string intent { get; set; }
        public Nullable<System.Guid> mailbox_id { get; set; }
        public string parent_type { get; set; }
        public Nullable<System.Guid> parent_id { get; set; }
        public string uid { get; set; }
        public string category_id { get; set; }
    }
}
