//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_addresses
    {
        public System.Guid id { get; set; }
        public string email_address { get; set; }
        public string email_address_caps { get; set; }
        public Nullable<bool> invalid_email { get; set; }
        public Nullable<bool> opt_out { get; set; }
        public string confirm_opt_in { get; set; }
        public Nullable<System.DateTime> confirm_opt_in_date { get; set; }
        public Nullable<System.DateTime> confirm_opt_in_sent_date { get; set; }
        public Nullable<System.DateTime> confirm_opt_in_fail_date { get; set; }
        public string confirm_opt_in_token { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
