//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class emailman
    {
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.Guid> user_id { get; set; }
        public int id { get; set; }
        public Nullable<System.Guid> campaign_id { get; set; }
        public Nullable<System.Guid> marketing_id { get; set; }
        public Nullable<System.Guid> list_id { get; set; }
        public Nullable<System.DateTime> send_date_time { get; set; }
        public Nullable<System.Guid> modified_user_id { get; set; }
        public Nullable<bool> in_queue { get; set; }
        public Nullable<System.DateTime> in_queue_date { get; set; }
        public Nullable<int> send_attempts { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.Guid> related_id { get; set; }
        public string related_type { get; set; }
        public Nullable<bool> related_confirm_opt_in { get; set; }
    }
}
