//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_marketing
    {
        public System.Guid id { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.Guid> modified_user_id { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public string name { get; set; }
        public string from_name { get; set; }
        public string from_addr { get; set; }
        public string reply_to_name { get; set; }
        public string reply_to_addr { get; set; }
        public string inbound_email_id { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public System.Guid template_id { get; set; }
        public string status { get; set; }
        public Nullable<System.Guid> campaign_id { get; set; }
        public Nullable<System.Guid> outbound_email_id { get; set; }
        public Nullable<bool> all_prospect_lists { get; set; }
    }
}
