//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class fields_meta_data
    {
        public string id { get; set; }
        public string name { get; set; }
        public string vname { get; set; }
        public string comments { get; set; }
        public string help { get; set; }
        public string custom_module { get; set; }
        public string type { get; set; }
        public Nullable<int> len { get; set; }
        public Nullable<bool> required { get; set; }
        public string default_value { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<bool> audited { get; set; }
        public Nullable<bool> massupdate { get; set; }
        public Nullable<short> duplicate_merge { get; set; }
        public Nullable<bool> reportable { get; set; }
        public string importable { get; set; }
        public string ext1 { get; set; }
        public string ext2 { get; set; }
        public string ext3 { get; set; }
        public string ext4 { get; set; }
    }
}
