//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class folder
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string folder_type { get; set; }
        public Nullable<System.Guid> parent_folder { get; set; }
        public Nullable<bool> has_child { get; set; }
        public Nullable<bool> is_group { get; set; }
        public Nullable<bool> is_dynamic { get; set; }
        public string dynamic_query { get; set; }
        public Nullable<System.Guid> assign_to_id { get; set; }
        public System.Guid created_by { get; set; }
        public System.Guid modified_by { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
