//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class folders_rel
    {
        public System.Guid id { get; set; }
        public System.Guid folder_id { get; set; }
        public string polymorphic_module { get; set; }
        public System.Guid polymorphic_id { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
