//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class fp_events_prospects_1_c
    {
        public string id { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string fp_events_prospects_1fp_events_ida { get; set; }
        public string fp_events_prospects_1prospects_idb { get; set; }
        public string invite_status { get; set; }
        public string accept_status { get; set; }
        public Nullable<int> email_responded { get; set; }
    }
}
