//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class fp_event_locations_fp_events_1_c
    {
        public string id { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string fp_event_locations_fp_events_1fp_event_locations_ida { get; set; }
        public string fp_event_locations_fp_events_1fp_events_idb { get; set; }
    }
}
