//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class inbound_email
    {
        public string id { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.Guid> modified_user_id { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public string name { get; set; }
        public string status { get; set; }
        public string server_url { get; set; }
        public string email_user { get; set; }
        public string email_password { get; set; }
        public Nullable<int> port { get; set; }
        public string service { get; set; }
        public string mailbox { get; set; }
        public Nullable<bool> delete_seen { get; set; }
        public string mailbox_type { get; set; }
        public Nullable<System.Guid> template_id { get; set; }
        public string stored_options { get; set; }
        public Nullable<System.Guid> group_id { get; set; }
        public Nullable<bool> is_personal { get; set; }
        public Nullable<System.Guid> groupfolder_id { get; set; }
    }
}
