//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_queue
    {
        public Nullable<System.Guid> assigned_user_id { get; set; }
        public System.Guid id { get; set; }
        public string name { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.Guid> scheduler_id { get; set; }
        public Nullable<System.DateTime> execute_time { get; set; }
        public string status { get; set; }
        public string resolution { get; set; }
        public string message { get; set; }
        public string target { get; set; }
        public string data { get; set; }
        public Nullable<bool> requeue { get; set; }
        public Nullable<sbyte> retry_count { get; set; }
        public Nullable<sbyte> failure_count { get; set; }
        public Nullable<int> job_delay { get; set; }
        public string client { get; set; }
        public Nullable<int> percent_complete { get; set; }
    }
}
