//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class lead
    {
        public System.Guid id { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.Guid> modified_user_id { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public string description { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.Guid> assigned_user_id { get; set; }
        public string salutation { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string title { get; set; }
        public string photo { get; set; }
        public string department { get; set; }
        public Nullable<bool> do_not_call { get; set; }
        public string phone_home { get; set; }
        public string phone_mobile { get; set; }
        public string phone_work { get; set; }
        public string phone_other { get; set; }
        public string phone_fax { get; set; }
        public string lawful_basis { get; set; }
        public Nullable<System.DateTime> date_reviewed { get; set; }
        public string lawful_basis_source { get; set; }
        public string primary_address_street { get; set; }
        public string primary_address_city { get; set; }
        public string primary_address_state { get; set; }
        public string primary_address_postalcode { get; set; }
        public string primary_address_country { get; set; }
        public string alt_address_street { get; set; }
        public string alt_address_city { get; set; }
        public string alt_address_state { get; set; }
        public string alt_address_postalcode { get; set; }
        public string alt_address_country { get; set; }
        public string assistant { get; set; }
        public string assistant_phone { get; set; }
        public Nullable<bool> converted { get; set; }
        public string refered_by { get; set; }
        public string lead_source { get; set; }
        public string lead_source_description { get; set; }
        public string status { get; set; }
        public string status_description { get; set; }
        public Nullable<System.Guid> reports_to_id { get; set; }
        public string account_name { get; set; }
        public string account_description { get; set; }
        public Nullable<System.Guid> contact_id { get; set; }
        public Nullable<System.Guid> account_id { get; set; }
        public Nullable<System.Guid> opportunity_id { get; set; }
        public string opportunity_name { get; set; }
        public string opportunity_amount { get; set; }
        public Nullable<System.Guid> campaign_id { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string portal_name { get; set; }
        public string portal_app { get; set; }
        public string website { get; set; }
    }
}
