//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class notes_cstm
    {
        public System.Guid id_c { get; set; }
        public string activitydetails_c { get; set; }
        public string status_c { get; set; }
        public string socialmedia_c { get; set; }
        public Nullable<int> recordid_c { get; set; }
    }
}
