//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class oauth_tokens
    {
        public System.Guid id { get; set; }
        public string secret { get; set; }
        public string tstate { get; set; }
        public System.Guid consumer { get; set; }
        public Nullable<long> token_ts { get; set; }
        public string verify { get; set; }
        public bool deleted { get; set; }
        public string callback_url { get; set; }
        public Nullable<System.Guid> assigned_user_id { get; set; }
    }
}
