//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using OrgBubbleDataViews;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class orgbubble_data_viewsEntities : DbContext
    {
        public orgbubble_data_viewsEntities()
            : base("name=orgbubble_data_viewsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<orgbubble_socialmedia_posts> orgbubble_socialmedia_posts { get; set; }
        public virtual DbSet<orgbubble_socialmedia_accounts> orgbubble_socialmedia_accounts { get; set; }
    }
}
