//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgBubbleDataViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class orgbubble_socialmedia_posts
    {
        public string socialmedia { get; set; }
        public int id { get; set; }
        public string ids { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> account { get; set; }
        public string category_or_type { get; set; }
        public string group { get; set; }
        public string type { get; set; }
        public string data { get; set; }
        public Nullable<System.DateTime> time_post { get; set; }
        public Nullable<int> delay { get; set; }
        public Nullable<int> time_delete { get; set; }
        public string result { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> changed { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
