//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgBubbleDataViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class orgbubble_socialmedia_accounts
    {
        public string socialmedia { get; set; }
        public string uid { get; set; }
        public string pid { get; set; }
        public string type { get; set; }
        public string fullname { get; set; }
        public string url { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> changed { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
