//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class outbound_email
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public System.Guid user_id { get; set; }
        public string smtp_from_name { get; set; }
        public string smtp_from_addr { get; set; }
        public string mail_sendtype { get; set; }
        public string mail_smtptype { get; set; }
        public string mail_smtpserver { get; set; }
        public string mail_smtpport { get; set; }
        public string mail_smtpuser { get; set; }
        public string mail_smtppass { get; set; }
        public Nullable<bool> mail_smtpauth_req { get; set; }
        public string mail_smtpssl { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.Guid> modified_user_id { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.Guid> assigned_user_id { get; set; }
    }
}
