//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_task
    {
        public System.Guid id { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public System.Guid project_id { get; set; }
        public Nullable<int> project_task_id { get; set; }
        public string name { get; set; }
        public string status { get; set; }
        public string relationship_type { get; set; }
        public string description { get; set; }
        public string predecessors { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<int> time_start { get; set; }
        public Nullable<int> time_finish { get; set; }
        public Nullable<System.DateTime> date_finish { get; set; }
        public Nullable<int> duration { get; set; }
        public string duration_unit { get; set; }
        public Nullable<int> actual_duration { get; set; }
        public Nullable<int> percent_complete { get; set; }
        public Nullable<System.DateTime> date_due { get; set; }
        public Nullable<System.TimeSpan> time_due { get; set; }
        public Nullable<int> parent_task_id { get; set; }
        public Nullable<System.Guid> assigned_user_id { get; set; }
        public Nullable<System.Guid> modified_user_id { get; set; }
        public string priority { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<bool> milestone_flag { get; set; }
        public Nullable<int> order_number { get; set; }
        public Nullable<int> task_number { get; set; }
        public Nullable<int> estimated_effort { get; set; }
        public Nullable<int> actual_effort { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<int> utilization { get; set; }
    }
}
