//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class scheduler
    {
        public string id { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<System.Guid> modified_user_id { get; set; }
        public string name { get; set; }
        public string job { get; set; }
        public Nullable<System.DateTime> date_time_start { get; set; }
        public Nullable<System.DateTime> date_time_end { get; set; }
        public string job_interval { get; set; }
        public Nullable<System.TimeSpan> time_from { get; set; }
        public Nullable<System.TimeSpan> time_to { get; set; }
        public Nullable<System.DateTime> last_run { get; set; }
        public string status { get; set; }
        public Nullable<bool> catch_up { get; set; }
    }
}
