//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class securitygroups_records
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> securitygroup_id { get; set; }
        public Nullable<System.Guid> record_id { get; set; }
        public Nullable<System.Guid> module { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.Guid> modified_user_id { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
