//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.Guid> modified_user_id { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public string description { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.Guid> assigned_user_id { get; set; }
        public string status { get; set; }
        public Nullable<bool> date_due_flag { get; set; }
        public Nullable<System.DateTime> date_due { get; set; }
        public Nullable<bool> date_start_flag { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public string parent_type { get; set; }
        public Nullable<System.Guid> parent_id { get; set; }
        public Nullable<System.Guid> contact_id { get; set; }
        public string priority { get; set; }
    }
}
