//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracker
    {
        public int id { get; set; }
        public System.Guid monitor_id { get; set; }
        public string user_id { get; set; }
        public string module_name { get; set; }
        public string item_id { get; set; }
        public string item_summary { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string action { get; set; }
        public string session_id { get; set; }
        public Nullable<bool> visible { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
