//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class upgrade_history
    {
        public System.Guid id { get; set; }
        public string filename { get; set; }
        public string md5sum { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public string version { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string id_name { get; set; }
        public string manifest { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<bool> enabled { get; set; }
    }
}
