//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSync.Models.OBDataSources.Systems
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public System.Guid id { get; set; }
        public string user_name { get; set; }
        public string user_hash { get; set; }
        public Nullable<bool> system_generated_password { get; set; }
        public Nullable<System.DateTime> pwd_last_changed { get; set; }
        public string authenticate_id { get; set; }
        public Nullable<bool> sugar_login { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<bool> is_admin { get; set; }
        public Nullable<bool> external_auth_only { get; set; }
        public Nullable<bool> receive_notifications { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.Guid> modified_user_id { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public string title { get; set; }
        public string photo { get; set; }
        public string department { get; set; }
        public string phone_home { get; set; }
        public string phone_mobile { get; set; }
        public string phone_work { get; set; }
        public string phone_other { get; set; }
        public string phone_fax { get; set; }
        public string status { get; set; }
        public string address_street { get; set; }
        public string address_city { get; set; }
        public string address_state { get; set; }
        public string address_country { get; set; }
        public string address_postalcode { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<bool> portal_only { get; set; }
        public Nullable<bool> show_on_employees { get; set; }
        public string employee_status { get; set; }
        public string messenger_id { get; set; }
        public string messenger_type { get; set; }
        public Nullable<System.Guid> reports_to_id { get; set; }
        public Nullable<bool> is_group { get; set; }
        public Nullable<bool> factor_auth { get; set; }
        public string factor_auth_interface { get; set; }
    }
}
