// <auto-generated />
namespace OBSync.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class newfields3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newfields3));
        
        string IMigrationMetadata.Id
        {
            get { return "201912180358541_newfields3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
